/* AUTO-GENERATED by sim/generate_world.py — do not edit */
#pragma once
#define TA_WORLD_M 2400.0
#define TA_BASE_ALT 4280.0
#define TA_SUMMIT_ALT 8849.0
#define TA_HM_SIZE 256
#define TA_SEA_LEVEL_SPO2 98.0
#define TA_DEATH_ZONE_M 8000.0
#define TA_HAPE_SPO2_TRIGGER 62.0
#define TA_HACE_CLARITY_TRIGGER 0.35
#define TA_HYPOTHERMIA_C 35.0
#define TA_SEVERE_HYPO_C 32.0
#define TA_COLLAPSE_SPO2 46.0
#define TA_DEATH_ZONE_HOURS 18.0
#define TA_BASE_CORE_C 36.8
#define TA_VO2_SEA 52.0
#define TA_O2_BOTTLE_MIN 6.0
#define TA_O2_FLOW_LPM 2.5
